apiVersion: batch/v1
kind: Job
metadata:
  name: pod-security-test-job
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: test-container
          #image: busybox:1.36
          image: sekhmetn/kube-hacking-image:0.0.2
          command: ["bash", "-c", "echo 'Pod security test success!';echo 'id:' && id; echo 'sudo id: ' && sudo id ; sleep 5"]
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              #cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts: []
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
      volumes: []
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000