apiVersion: v1
kind: Pod
metadata:
  name: pod-security-test
spec:
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  initContainers:
    - name: test-initcontainer
      image: sekhmetn/kube-hacking-image:0.0.2
      # Run chmod and chown on the mounted volume
      command: ["bash", "-c", "echo 'Pod security test success!';echo 'id:' && id; echo 'sudo id: ' && sudo id ; sleep 5"]
      resources:
        limits:
          #cpu: "400m"
          memory: "8Mi"
        requests:
          cpu: "200m"
          memory: "2Mi"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
  containers:
    - name: test-container
      #image: busybox:1.36
      image: sekhmetn/kube-hacking-image:0.0.2
      command: ["bash", "-c", "echo 'Pod security test success!';echo 'id:' && id; echo 'sudo id: ' && sudo id ; sleep 5"]
      resources:
        limits:
          #cpu: "1"
          memory: "256Mi"
        requests:
          cpu: "200m"
          memory: "256Mi"
      volumeMounts: []
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
  volumes: []
