apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: Pod
      name: pod-security-test
    patch: |-
      - op: add
        path: /spec/containers/0/ports
        value:
          - containerPort: 8080
            hostPort: 8080
            protocol: TCP
      - op: add
        path: /metadata/annotations/virtuekube.io~1test-title
        value: "HostPort exposed"
      - op: add
        path: /metadata/annotations/virtuekube.io~1test-description
        value: "Container exposes a hostPort. Disallowed by Restricted unless justified."
      - op: add
        path: /metadata/annotations/virtuekube.io~1test-references
        value: "https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted"
      - op: add
        path: /metadata/annotations/virtuekube.io~1test-expected-result
        value: false
