apiVersion: v1
kind: Pod
metadata:  
  labels:
    app: kube-hacking
  name: kube-hacking
spec:
  containers:
  - image: sekhmetn/kube-hacking-image:latest
    imagePullPolicy: Always
    name: kube-hacking
    command: ["sleep"]
    args: ["8h"]
    resources:
      requests:
        cpu: "200m"
        memory: "4Mi"
      limits:
        cpu: "400m"
        memory: "8Mi"      
    securityContext: # Added for Kyverno medium risk policies
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000 # Example non-root user ID
      runAsGroup: 1000
      capabilities:
        drop:
          - ALL
        #add:
          #- NET_BIND_SERVICE
  serviceAccount: default
  serviceAccountName: default  
  terminationGracePeriodSeconds: 30